carts/urls.py
from django.conf.urls import url

from .views import (
    cart_home, 
    cart_update,
    checkout_home,
    checkout_done_view
    )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^update/$', cart_update, name='update'),
]

ecommerce/urls.py
#Para usar archivos staticos en desarrollo
#en produccion es diferente 
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from accounts.views import LoginView, RegisterView, guest_register_view
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from billing.views import payment_method_view, payment_method_create_view
from carts.views import cart_datail_api_view
from .views import  home_page, about_page, contact_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest$', guest_register_view, name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_datail_api_view, name='api-cart'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_create_view, name='billing-payment-method-endpoint'),
    url(r'^about/$', about_page, name='about'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^contact/$', contact_page, name='contact'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns =  urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns =  urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
    ProductListView, 
    ProductDetailSlugView, 
    )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
]

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>


<!-- FontAwesome CSS-->
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


<!-- Jquery confirm CSS-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">


<!-- Custom Stripe CSS-->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

templates/base/js-templates.html
{% verbatim %}
<!--Stripe templete form-->
<script id="stripeTemplate" type="text/x-jsrender">
 <form class="payment-form" action="" method="post" id="payment-form" 
    data-token='{{:publishKey }}'  data-next-url='{{:nextUrl }}'>
    <div class="form-row">
        <!--<label for="card-element">
          Credit or debit card
        </label>-->
        <div id="card-element" class="form-control">
        </div>
         <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
    </div>
    
    <button class="btn btn-primary my-3">{{:btnTitle}}</button>
</form>
</script>

{% endverbatim %}

templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<!-- Jquery Confirm JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

<!--JS Render-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.88/jsrender.min.js"></script>
{% include "base/js-templates.html" %}

<!--Django Secure AJAX JS-->
<script src='{% static "js/csrf.ajax.js"%}'></script>

<!--eCommerce Custom JS-->
<script src='{% static "js/ecommerce.js"%}'></script>

<!--eCommerce Custom Main JS-->
<script src='{% static "js/ecommerce.main.js"%}'></script>

<!--Stripe JS-->
<script src="https://js.stripe.com/v3/"></script>

templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'login' as login_url%}
{% url 'logout' as logout_url%}
{% url 'register' as register_url%}
{% url 'about' as about_url%}
{% url 'cart:home' as cart_url%}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
<div class="container">
  <a class="navbar-brand" href="{{home_url}}">
    <img src="https://www.getbootstrap.com/docs/4.3/assets/brand/bootstrap-solid.svg" 
    width="30" height="30" class="d-inline-block align-top" alt="">
    {% if brand_name %}
      {{ brand_name}}  
    {% else %}
        Bankai ECommerce  
    {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link {% if request.path == home_url %}active{% endif %}" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == contact_url %}active{% endif %}" href="{{contact_url}}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == about_url %}active{% endif %}" href="{{about_url}}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == products_list_url %}active{% endif %}" href="{{products_list_url}}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == logout_url %}active{% endif %}" href="{{logout_url}}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link {% if request.path == register_url %}active{% endif %}" href="{{register_url}}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == login_url %}active{% endif %}" href="{{login_url}}">Login</a>
        </li>
      {% endif %}
      <li class="nav-item">
          <a class="nav-link {% if request.path == cart_url %}active{% endif %}" href="{{cart_url}}">
            <span class="navbar-cart-count">{{ request.session.cart_items }} 
            </span>
            <i class="fa fa-shopping-cart" ></i>
          </a>
        </li>
      <!--<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
          </a>
          <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>   -->
    </lu>
    {% include 'search/snippets/search-form.html' %}
  </div>
</div>
</nav>